### ISSUE TITLE
Path separators are mixed when diffing files in subfolders

### ISSUE THREAD

**Issue by keith-hall** [OdatNurd/OverrideAudit#14]
When diffing an override that is contained within a subfolder of a package, the diff header mixes path separators.

```diff
--- Installed Packages\OverrideAudit\messages/install.txt   2017-04-04 08:20:16
+++ Packages\OverrideAudit\messages/install.txt 2017-04-04 09:07:01
@@ -1,5 +1,7 @@
 OverrideAudit
 =============
+
+© OdatNurd 2017 
 OverrideAudit helps you keep track of all of your package overrides, easily
 allowing you to see what overrides are in place, how they're different from the
```

# Steps to reproduce:

0. Open Command Palette
0. Select `PackageResourceViewer: Open Resource`
0. Select `OverrideAudit`
0. Select `messages`
0. Select `install.txt`
0. Make a small change
0. Save it
0. Right click on the tab and select `OverrideAudit: Diff Override`
0. Notice that the diff header shows a path with both `/` and `\` style path separators

# Expected behavior:

The diff would show only a single style of path separator. It might make sense to use the path separator that is used by the current OS. Although, saying that, I use Windows and would be quite happy to see Unix style path separators used exclusively, but probably I'm the odd one out there. ;)

# Environment

Sublime Text build: 3125
OverrideAudit: v1.0.0
Operating System: Windows
Case Sensitive Filesystem: No

**Comment by OdatNurd** [comment]
This should be easy to fix by normalizing the displayed path to the path separator for the current OS. I'll also cast around because this probably occurs elsewhere as well. At the least it's also present in error messages during diffing when files are not found and in some status bar messages.

I would agree that the path convention for the current OS makes the most sense here, although apart from full paths, all overrides within a sub path are displayed with a unix-style path separator because that's how they're portrayed inside of the `sublime-package` files.

**Comment by FichteFoll** [comment]
You could also unify them to use forward slashes because that's what ST uses for its relative pathes to the data directory (e.g. `View.assign_syntax`, `color_scheme` setting).

**Comment by OdatNurd** [comment]
Yeah, everything here is rooted in the Data directory with the exception of shipped packages, although that's just a technicality and the paths are always portrayed as relative. 

I hadn't considered that Sublime itself always uses the other path style internally, so that would make things more consistent, especially since override files with path segments in them always use that style anyway, so it would be consistent with itself and Sublime at the same time.
