### ISSUE TITLE
[FEATURE] Tab context menu item to revert an override

### ISSUE THREAD

**Issue by keith-hall** [OdatNurd/OverrideAudit#26]
### Summary

I really like the context menu on the tab that allows one to diff or delete the current override.
![image](https://user-images.githubusercontent.com/11882719/30594962-77e28686-9d58-11e7-91f3-403215323bae.png)

I would find it really useful to also have an option to revert an override.

### Expected Behaviour

Open an override, right click the tab and see a menu item to revert the override. This would unpack the original file and replace the contents of the current buffer with that.

### Actual Behaviour

Have an override open, maybe even perform a diff, and see that you want to start fresh from the original file. Right click the tab and choose `Delete Override`. Close the tab, and then go through the whole process of finding and opening the file again from PackageResourceViewer.

**Comment by OdatNurd** [comment]
This functionality seems like it would be handy from the context menu/command palette in either a diff of an override or an edit of one, but not from other places like the context menu in a report, since in that case deleting the override is the same as reverting as you don't already have it open. Am I missing any other places where it might be handy that I'm not thinking of at the moment?

Other things to consider are what happens to an open edit buffer if you revert.Basically it would pull the base content and run a replace on the view to replace the entire contents if the file was opened, or replace the file on disk if it's not currently open (i.e. a diff).

There's also:
  * Should it save the file after it's done that (in the open case) so it's officially persisted, or leave the buffer modified but un-persisted? 
  * Should it try to keep your rough edit position if possible or just jump to the top of the file? Maybe try to keep the same relative lines visible if the reverted file is close enough in length line-wise, otherwise jump to the top?
 * Presumably a confirmation dialog would also be displayed as when deleting to make sure you meant to do it, with the ability to disable like the other commands have.

**Comment by OdatNurd** [comment]
This is now implemented in OverrideAudit 2.1.0; the command will replace the content of the override with the underlying content of that package. Note that unlike deleting an override (which moves the file to the trash), this overwrites the file. So, it's important to keep a backup (or put your package in git) if you want to get the content back.

For the moment if the file happens to be open Sublime will just reload it as it normally would, so your edit position is lost for that case.
