### ISSUE TITLE
[BUG] OverrideAudit confuses ST's minidiff

### ISSUE THREAD

**Issue by deathaxe** [OdatNurd/OverrideAudit#31]
### Summary

ST's mini diff has started displaying totally wrong markers on certain files. It looks like the reference document used to create the diff, is heavily outdated.

I am able to reproduce this issue for sure by enabling/disabling OverrideAudit.

### Expected Behaviour

When opening a git tracked _Packages/Perl/Perl.sublime-syntax_ file, the mini diff should only show markers on lines which have not been committed yet.

### Actual Behaviour

The mini diff shows markers on many more lines even if the whole file is commited to git.

### How to Reproduce

1. Install a vanilla ST
2. Clone https://github.com/sublimehq/Packages to any location outside of the new installed ST
3. Create a junction of a single syntax package from 2) into _Data/Packages/_ of 1) (e.g.: Perl)
4. Install OverrideAudit
5. Run: Add the folder command to add 3) (e.g.: _Data/Packages/Perl_)
6. Open (or close and open) a Perl.sublime-syntax from the sidebar.

_Note: The Syntax Package should contain changes compared to the shipped builtin syntax packages to trigger the bug._

### Environment

- Sublime Text build: 3207, 3210
- OverrideAudit version: v2.1.0
- Operating System: Windows 10
- Case Sensitive Filesystem: No

**Comment by OdatNurd** [comment]
I think what you're seeing here is the new behaviour added in OverrideAudit 2.1. A new setting was added called `mini_diff_underlying`, which defaults to being turned on,

When that setting is enabled and you edit an override of a package file, OA sets up the reference document to be the version of the file in the `sublime-package` file so that the incremental diff will show you how the override is different from the base file.

If you set `mini_diff_underlying` to `false` in the OA settings and re-open the file, the diff should go back to what it was before. 

This does get in the way if you're working on a package tracked by git that's also represented as a `sublime-package` file though, assuming you want to see the changes to the file based on git and not the underlying package. There's not currently a way to disable the feature on a package by package basis. 

There are a few ways around that but I'm not sure which is better. The existing setting could be enhanced to allow you to disable it for specific packages, or there could be an alternate setting to disable it specifically for packages tracked by git.

Detecting whether a folder represents a git repository (or a part of one if it's a symlink) seems non-trivial though, in that I don't have a lot of experience with the variety of ways that this can happen (most of the errors in Merge not being able to detect working directories were a surprise to me, for example).

**Comment by deathaxe** [comment]
> If you set `mini_diff_underlying` to `false`

It did the trick. I am fine with it.

Wasn't aware about that at all.

> There are a few ways around that ... Detecting whether a folder represents a git repository (or a part of one if it's a symlink) seems non-trivial

It isn't too complicated for that purpose in the end, but I don't think it's within the scope of the plugin to handle git related lowlevel functions. 

I'd expect Sublime Text to provide those informations via API. Now that it has a very fast readonly git library implementet which already handles all the symblink/worktree/... stuff, it should enable plugins to make use of it.

Something like the following functions are the least, I'd expect.

- `view.is_vcs_tracked()` - is file under version control
- `view.vcs_worktree_root()`  - worktree root directory without resolving symlinks
- `view.vcs_real_worktree_root()` - path to the real worktree root with symlinks resolved
