### ISSUE TITLE
[FEATURE] Override report (or Bulk Diff) showing only modified/deleted/new files

### ISSUE THREAD

**Issue by michaelblyons** [OdatNurd/OverrideAudit#35]
### Summary

A specialized Override Report that only shows files that are different from the base _OR_ a way to skip unmodified files in the Bulk Diff Report (and I'd code fold to level 2).

### Raison d'Etre

I have full package overrides for lots of Shipped Packages, but most of those files are unmodified. There are dozens of snippets I've never even looked at. They all show up in OA reports. When I do an Audit, what I really care about are the files I've added, deleted, or changed.

The default OA behaviour works really well if you're using OA to tweak a single file for personal use, but not as well when you're developing or integrating changes to `sublimehq/Packages`.

### Extra information

This package rocks.

**Comment by FichteFoll** [comment]
Potentially a duplicate of #34.

**Comment by michaelblyons** [comment]
Negative, FF. That might be useful, too, but I mean this:


<img width="951" alt="Screen Shot 2020-05-22 at 2 27 53 PM" src="https://user-images.githubusercontent.com/2701605/82698328-1a45e780-9c5a-11ea-95c5-4ad93a145074.png">

**Comment by FichteFoll** [comment]
Ah, I see, this is the manually requested report. Then it's just related.

**Comment by OdatNurd** [comment]
I've completed some prototype changes that implement this for Override reports. The command that generates them takes a new option that causes it to diff overrides and exclude them from the report of their content is not changed.

This doesn't apply to binary files (since currently they don't get diffed, although some changes are pending that would at least detect changes based on checksums), and it will also (or should anyway) still let through an override that appears unchanged but which is expired.

This isn't implemented yet for bulk diffs though. It seems fairly clean to be able to generate an override report either way, since you may want to know what's changed even if it hasn't, but for the purposes of bulk diffs it seems like this may be better suited to a new setting that just causes all diff reports to always exclude unchanged files. The logic here is that those reports are for showing you what's different, so it seems to make sense to just hide unchanged files as uninteresting.

Thoughts?

**Comment by michaelblyons** [comment]
Good enough for showing me which things I might want to bulk diff.
